/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ALLOW_INSECURE_IV_FALLBACK 0

#define HAVE_CLOCK_GETTIME 1

#define HAVE_LIBMICROHTTPD 0

#define HAVE_MBEDTLS 1

#define HAVE_NETTLE 0

#define HAVE_PROMETHEUS_SUPPORT 1

#define HAVE_PTHREADS 1

#define HAVE_SOCK_UN_H 1

#define MBEDTLS_HAS_MPI_RANDOM 0

